# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_Export(object):
    def setupUi(self, Dialog_Export):
        Dialog_Export.setObjectName("Dialog_Export")
        Dialog_Export.resize(463, 393)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_Export)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_Export)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_FreqNum = QtWidgets.QLineEdit(Dialog_Export)
        self.lineEdit_FreqNum.setObjectName("lineEdit_FreqNum")
        self.verticalLayout.addWidget(self.lineEdit_FreqNum)
        self.label_2 = QtWidgets.QLabel(Dialog_Export)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_Freq = QtWidgets.QVBoxLayout()
        self.verticalLayout_Freq.setObjectName("verticalLayout_Freq")
        self.verticalLayout.addLayout(self.verticalLayout_Freq)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(Dialog_Export)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.radioButton_AllSource = QtWidgets.QRadioButton(Dialog_Export)
        self.radioButton_AllSource.setCheckable(True)
        self.radioButton_AllSource.setChecked(True)
        self.radioButton_AllSource.setAutoExclusive(False)
        self.radioButton_AllSource.setObjectName("radioButton_AllSource")
        self.verticalLayout_2.addWidget(self.radioButton_AllSource)
        self.radioButton_RangeSource = QtWidgets.QRadioButton(Dialog_Export)
        self.radioButton_RangeSource.setChecked(False)
        self.radioButton_RangeSource.setAutoExclusive(False)
        self.radioButton_RangeSource.setObjectName("radioButton_RangeSource")
        self.verticalLayout_2.addWidget(self.radioButton_RangeSource)
        self.horizontalLayout_SourceRange = QtWidgets.QHBoxLayout()
        self.horizontalLayout_SourceRange.setObjectName("horizontalLayout_SourceRange")
        self.comboBox_Source1 = QtWidgets.QComboBox(Dialog_Export)
        self.comboBox_Source1.setEnabled(False)
        self.comboBox_Source1.setObjectName("comboBox_Source1")
        self.horizontalLayout_SourceRange.addWidget(self.comboBox_Source1)
        self.label_5 = QtWidgets.QLabel(Dialog_Export)
        self.label_5.setEnabled(False)
        self.label_5.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_SourceRange.addWidget(self.label_5)
        self.comboBox_Source2 = QtWidgets.QComboBox(Dialog_Export)
        self.comboBox_Source2.setEnabled(False)
        self.comboBox_Source2.setObjectName("comboBox_Source2")
        self.horizontalLayout_SourceRange.addWidget(self.comboBox_Source2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_SourceRange)
        self.label_3 = QtWidgets.QLabel(Dialog_Export)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog_Export)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.radioButton_AllReceiver = QtWidgets.QRadioButton(Dialog_Export)
        self.radioButton_AllReceiver.setChecked(True)
        self.radioButton_AllReceiver.setAutoExclusive(False)
        self.radioButton_AllReceiver.setObjectName("radioButton_AllReceiver")
        self.verticalLayout_2.addWidget(self.radioButton_AllReceiver)
        self.radioButton_RangeReceiver = QtWidgets.QRadioButton(Dialog_Export)
        self.radioButton_RangeReceiver.setAutoExclusive(False)
        self.radioButton_RangeReceiver.setObjectName("radioButton_RangeReceiver")
        self.verticalLayout_2.addWidget(self.radioButton_RangeReceiver)
        self.horizontalLayout_ReceiverRange = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ReceiverRange.setObjectName("horizontalLayout_ReceiverRange")
        self.comboBox_Receiver1 = QtWidgets.QComboBox(Dialog_Export)
        self.comboBox_Receiver1.setEnabled(False)
        self.comboBox_Receiver1.setObjectName("comboBox_Receiver1")
        self.horizontalLayout_ReceiverRange.addWidget(self.comboBox_Receiver1)
        self.label_6 = QtWidgets.QLabel(Dialog_Export)
        self.label_6.setEnabled(False)
        self.label_6.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_ReceiverRange.addWidget(self.label_6)
        self.comboBox_Receiver2 = QtWidgets.QComboBox(Dialog_Export)
        self.comboBox_Receiver2.setEnabled(False)
        self.comboBox_Receiver2.setObjectName("comboBox_Receiver2")
        self.horizontalLayout_ReceiverRange.addWidget(self.comboBox_Receiver2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_ReceiverRange)
        self.label_Direction = QtWidgets.QLabel(Dialog_Export)
        self.label_Direction.setEnabled(True)
        self.label_Direction.setObjectName("label_Direction")
        self.verticalLayout_2.addWidget(self.label_Direction)
        self.comboBox_Direction = QtWidgets.QComboBox(Dialog_Export)
        self.comboBox_Direction.setObjectName("comboBox_Direction")
        self.verticalLayout_2.addWidget(self.comboBox_Direction)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Export)
        self.buttonBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Dialog_Export)
        self.label_7.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEdit_Path = QtWidgets.QLineEdit(Dialog_Export)
        self.lineEdit_Path.setObjectName("lineEdit_Path")
        self.horizontalLayout_4.addWidget(self.lineEdit_Path)
        self.pushButton_Open = QtWidgets.QPushButton(Dialog_Export)
        self.pushButton_Open.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.horizontalLayout_4.addWidget(self.pushButton_Open)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)

        self.retranslateUi(Dialog_Export)
        self.buttonBox.accepted.connect(Dialog_Export.accept)
        self.buttonBox.rejected.connect(Dialog_Export.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Export)

    def retranslateUi(self, Dialog_Export):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Export.setWindowTitle(_translate("Dialog_Export", "Export"))
        self.label.setText(_translate("Dialog_Export", "Freq Num:"))
        self.label_2.setText(_translate("Dialog_Export", "Freq:"))
        self.label_8.setText(_translate("Dialog_Export", "Source Num:"))
        self.radioButton_AllSource.setText(_translate("Dialog_Export", "All Source"))
        self.radioButton_RangeSource.setText(_translate("Dialog_Export", "Range:"))
        self.label_5.setText(_translate("Dialog_Export", "-"))
        self.label_3.setText(_translate("Dialog_Export", "========================"))
        self.label_4.setText(_translate("Dialog_Export", "Receiver Num:"))
        self.radioButton_AllReceiver.setText(_translate("Dialog_Export", "All Receiver"))
        self.radioButton_RangeReceiver.setText(_translate("Dialog_Export", "Range:"))
        self.label_6.setText(_translate("Dialog_Export", "-"))
        self.label_Direction.setText(_translate("Dialog_Export", "Direction:"))
        self.label_7.setText(_translate("Dialog_Export", "ExportPath:"))
        self.pushButton_Open.setText(_translate("Dialog_Export", "Open"))

