# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TracesSettingUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TracesSetting(object):
    def setupUi(self, TracesSetting):
        TracesSetting.setObjectName("TracesSetting")
        TracesSetting.resize(370, 412)
        self.verticalLayout = QtWidgets.QVBoxLayout(TracesSetting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(TracesSetting)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.FirstLineEdit = QtWidgets.QLineEdit(TracesSetting)
        self.FirstLineEdit.setObjectName("FirstLineEdit")
        self.horizontalLayout.addWidget(self.FirstLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(TracesSetting)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.IntervalEdit = QtWidgets.QLineEdit(TracesSetting)
        self.IntervalEdit.setObjectName("IntervalEdit")
        self.horizontalLayout_2.addWidget(self.IntervalEdit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(TracesSetting)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.GainEdit = QtWidgets.QLineEdit(TracesSetting)
        self.GainEdit.setObjectName("GainEdit")
        self.horizontalLayout_4.addWidget(self.GainEdit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.label_4 = QtWidgets.QLabel(TracesSetting)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.ShowNumEdit = QtWidgets.QLineEdit(TracesSetting)
        self.ShowNumEdit.setEnabled(False)
        self.ShowNumEdit.setDragEnabled(False)
        self.ShowNumEdit.setReadOnly(False)
        self.ShowNumEdit.setObjectName("ShowNumEdit")
        self.horizontalLayout_5.addWidget(self.ShowNumEdit)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.checkBox_fft = QtWidgets.QCheckBox(TracesSetting)
        self.checkBox_fft.setObjectName("checkBox_fft")
        self.horizontalLayout_3.addWidget(self.checkBox_fft)
        self.checkBox_Color = QtWidgets.QCheckBox(TracesSetting)
        self.checkBox_Color.setObjectName("checkBox_Color")
        self.horizontalLayout_3.addWidget(self.checkBox_Color)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.buttonBox = QtWidgets.QDialogButtonBox(TracesSetting)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(TracesSetting)
        self.buttonBox.accepted.connect(TracesSetting.accept)
        self.buttonBox.rejected.connect(TracesSetting.reject)
        QtCore.QMetaObject.connectSlotsByName(TracesSetting)

    def retranslateUi(self, TracesSetting):
        _translate = QtCore.QCoreApplication.translate
        TracesSetting.setWindowTitle(_translate("TracesSetting", "TracesSetting"))
        self.label.setText(_translate("TracesSetting", "FirstTrace："))
        self.label_2.setText(_translate("TracesSetting", "Interval："))
        self.label_3.setText(_translate("TracesSetting", "   Gain："))
        self.label_4.setText(_translate("TracesSetting", "ShowNum："))
        self.checkBox_fft.setText(_translate("TracesSetting", "fft(log)"))
        self.checkBox_Color.setText(_translate("TracesSetting", "Color"))

