# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1494, 910)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.checkBox_filter = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_filter.setObjectName("checkBox_filter")
        self.horizontalLayout_5.addWidget(self.checkBox_filter)
        self.pushButton_color = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_color.setObjectName("pushButton_color")
        self.horizontalLayout_5.addWidget(self.pushButton_color)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 0, 5, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Gain = QtWidgets.QLabel(self.centralwidget)
        self.label_Gain.setObjectName("label_Gain")
        self.horizontalLayout_4.addWidget(self.label_Gain)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMaxLength(5)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_nX = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nX.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_nX.setObjectName("lineEdit_nX")
        self.horizontalLayout_4.addWidget(self.lineEdit_nX)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_nY = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nY.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_nY.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_nY.setObjectName("lineEdit_nY")
        self.horizontalLayout_4.addWidget(self.lineEdit_nY)
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_4.addWidget(self.okButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 0, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(70)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem2)
        self.pushButton_SingleTrace = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SingleTrace.setObjectName("pushButton_SingleTrace")
        self.verticalLayout_1.addWidget(self.pushButton_SingleTrace)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem3)
        self.pushButton_Traces = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Traces.setObjectName("pushButton_Traces")
        self.verticalLayout_1.addWidget(self.pushButton_Traces)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem4)
        self.pushButton_AllTraces = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AllTraces.setObjectName("pushButton_AllTraces")
        self.verticalLayout_1.addWidget(self.pushButton_AllTraces)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem5)
        self.pushButton_CRG = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CRG.setObjectName("pushButton_CRG")
        self.verticalLayout_1.addWidget(self.pushButton_CRG)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem6)
        self.pushButton_CSG = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CSG.setObjectName("pushButton_CSG")
        self.verticalLayout_1.addWidget(self.pushButton_CSG)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem7)
        self.gridLayout_9.addLayout(self.verticalLayout_1, 1, 0, 1, 1)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.FunSelectionLabel = QtWidgets.QLabel(self.centralwidget)
        self.FunSelectionLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.FunSelectionLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.FunSelectionLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FunSelectionLabel.setAutoFillBackground(False)
        self.FunSelectionLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FunSelectionLabel.setTextFormat(QtCore.Qt.AutoText)
        self.FunSelectionLabel.setWordWrap(False)
        self.FunSelectionLabel.setObjectName("FunSelectionLabel")
        self.horizontalLayout_1.addWidget(self.FunSelectionLabel)
        self.gridLayout_9.addLayout(self.horizontalLayout_1, 0, 0, 1, 1)
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.gridLayout_9.addLayout(self.gridLayout_1, 1, 2, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1494, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuExport = QtWidgets.QMenu(self.menu)
        self.menuExport.setObjectName("menuExport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.action_Freq_Segy = QtWidgets.QAction(MainWindow)
        self.action_Freq_Segy.setObjectName("action_Freq_Segy")
        self.actionAcoustic = QtWidgets.QAction(MainWindow)
        self.actionAcoustic.setObjectName("actionAcoustic")
        self.actionElastic = QtWidgets.QAction(MainWindow)
        self.actionElastic.setObjectName("actionElastic")
        self.menuExport.addAction(self.action_Freq_Segy)
        self.menuExport.addAction(self.actionAcoustic)
        self.menuExport.addAction(self.actionElastic)
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.menuExport.menuAction())
        self.menu.addAction(self.actionInfo)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SeismicPlotMain"))
        self.checkBox_filter.setText(_translate("MainWindow", "Filter"))
        self.pushButton_color.setText(_translate("MainWindow", "Color"))
        self.label_Gain.setText(_translate("MainWindow", "Gain:"))
        self.lineEdit.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "nX:"))
        self.lineEdit_nX.setText(_translate("MainWindow", "10"))
        self.label_2.setText(_translate("MainWindow", "nY:"))
        self.lineEdit_nY.setText(_translate("MainWindow", "10"))
        self.okButton.setText(_translate("MainWindow", "Enter"))
        self.pushButton_SingleTrace.setText(_translate("MainWindow", "SingleTrace"))
        self.pushButton_Traces.setText(_translate("MainWindow", "Traces"))
        self.pushButton_AllTraces.setText(_translate("MainWindow", "AllTraces"))
        self.pushButton_CRG.setText(_translate("MainWindow", "CRG"))
        self.pushButton_CSG.setText(_translate("MainWindow", "CSG"))
        self.FunSelectionLabel.setText(_translate("MainWindow", "功能选择"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.action_Freq_Segy.setText(_translate("MainWindow", "Freq Segy"))
        self.actionAcoustic.setText(_translate("MainWindow", "Acoustic Segy"))
        self.actionElastic.setText(_translate("MainWindow", "Elastic Segy"))

