# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BandPassFilterDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BandPassFilterDialog(object):
    def setupUi(self, BandPassFilterDialog):
        BandPassFilterDialog.setObjectName("BandPassFilterDialog")
        BandPassFilterDialog.resize(556, 551)
        self.verticalLayout = QtWidgets.QVBoxLayout(BandPassFilterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_A_stop = QtWidgets.QLineEdit(BandPassFilterDialog)
        self.lineEdit_A_stop.setObjectName("lineEdit_A_stop")
        self.horizontalLayout_4.addWidget(self.lineEdit_A_stop)
        self.label_8 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_F_stop1 = QtWidgets.QLineEdit(BandPassFilterDialog)
        self.lineEdit_F_stop1.setObjectName("lineEdit_F_stop1")
        self.horizontalLayout_5.addWidget(self.lineEdit_F_stop1)
        self.label_10 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(BandPassFilterDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_F_pass1 = QtWidgets.QLineEdit(BandPassFilterDialog)
        self.lineEdit_F_pass1.setObjectName("lineEdit_F_pass1")
        self.horizontalLayout.addWidget(self.lineEdit_F_pass1)
        self.label_11 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.label_2 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_F_pass2 = QtWidgets.QLineEdit(BandPassFilterDialog)
        self.lineEdit_F_pass2.setObjectName("lineEdit_F_pass2")
        self.horizontalLayout_3.addWidget(self.lineEdit_F_pass2)
        self.label_12 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.label_5 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_F_stop2 = QtWidgets.QLineEdit(BandPassFilterDialog)
        self.lineEdit_F_stop2.setObjectName("lineEdit_F_stop2")
        self.horizontalLayout_8.addWidget(self.lineEdit_F_stop2)
        self.label_13 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.label_6 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.lineEdit_A_pass = QtWidgets.QLineEdit(BandPassFilterDialog)
        self.lineEdit_A_pass.setObjectName("lineEdit_A_pass")
        self.horizontalLayout_9.addWidget(self.lineEdit_A_pass)
        self.label_9 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.label_7 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit_fs = QtWidgets.QLineEdit(BandPassFilterDialog)
        self.lineEdit_fs.setEnabled(False)
        self.lineEdit_fs.setObjectName("lineEdit_fs")
        self.horizontalLayout_10.addWidget(self.lineEdit_fs)
        self.label_14 = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_jpg = QtWidgets.QLabel(BandPassFilterDialog)
        self.label_jpg.setMinimumSize(QtCore.QSize(530, 219))
        self.label_jpg.setObjectName("label_jpg")
        self.horizontalLayout_2.addWidget(self.label_jpg)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem15)
        self.buttonBox = QtWidgets.QDialogButtonBox(BandPassFilterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(BandPassFilterDialog)
        self.buttonBox.accepted.connect(BandPassFilterDialog.accept)
        self.buttonBox.rejected.connect(BandPassFilterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BandPassFilterDialog)

    def retranslateUi(self, BandPassFilterDialog):
        _translate = QtCore.QCoreApplication.translate
        BandPassFilterDialog.setWindowTitle(_translate("BandPassFilterDialog", "BandPassFilterDialog"))
        self.label_3.setText(_translate("BandPassFilterDialog", "A_stop :"))
        self.lineEdit_A_stop.setToolTip(_translate("BandPassFilterDialog", "<html><head/><body><p>Attenuation in the first stopband = dB</p></body></html>"))
        self.lineEdit_A_stop.setText(_translate("BandPassFilterDialog", "60"))
        self.label_8.setText(_translate("BandPassFilterDialog", "dB"))
        self.label_4.setText(_translate("BandPassFilterDialog", "F_stop1:"))
        self.lineEdit_F_stop1.setToolTip(_translate("BandPassFilterDialog", "<html><head/><body><p>Edge of the stopband =  Hz</p></body></html>"))
        self.lineEdit_F_stop1.setText(_translate("BandPassFilterDialog", "50"))
        self.label_10.setText(_translate("BandPassFilterDialog", "Hz"))
        self.label.setText(_translate("BandPassFilterDialog", "F_pass1:"))
        self.lineEdit_F_pass1.setToolTip(_translate("BandPassFilterDialog", "<html><head/><body><p>Edge of the passband =  Hz</p></body></html>"))
        self.lineEdit_F_pass1.setText(_translate("BandPassFilterDialog", "100"))
        self.label_11.setText(_translate("BandPassFilterDialog", "Hz"))
        self.label_2.setText(_translate("BandPassFilterDialog", "F_pass2:"))
        self.lineEdit_F_pass2.setToolTip(_translate("BandPassFilterDialog", "<html><head/><body><p>Closing edge of the passband =  Hz</p></body></html>"))
        self.lineEdit_F_pass2.setText(_translate("BandPassFilterDialog", "400"))
        self.label_12.setText(_translate("BandPassFilterDialog", "Hz"))
        self.label_5.setText(_translate("BandPassFilterDialog", "F_stop2:"))
        self.lineEdit_F_stop2.setToolTip(_translate("BandPassFilterDialog", "<html><head/><body><p>Edge of the second stopband =  Hz</p></body></html>"))
        self.lineEdit_F_stop2.setText(_translate("BandPassFilterDialog", "450"))
        self.label_13.setText(_translate("BandPassFilterDialog", "Hz"))
        self.label_6.setText(_translate("BandPassFilterDialog", "A_pass :"))
        self.lineEdit_A_pass.setToolTip(_translate("BandPassFilterDialog", "<html><head/><body><p>Amount of ripple allowed in the passband =  dB</p></body></html>"))
        self.lineEdit_A_pass.setText(_translate("BandPassFilterDialog", "0.5"))
        self.label_9.setText(_translate("BandPassFilterDialog", "dB"))
        self.label_7.setText(_translate("BandPassFilterDialog", "  f s  :"))
        self.lineEdit_fs.setToolTip(_translate("BandPassFilterDialog", "<html><head/><body><p>sampling freq</p></body></html>"))
        self.lineEdit_fs.setText(_translate("BandPassFilterDialog", "4000"))
        self.label_14.setText(_translate("BandPassFilterDialog", "Hz"))
        self.label_jpg.setText(_translate("BandPassFilterDialog", "JPGLabel"))

